Models/ErrorViewModel.cs
namespace AppAzure.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Funcionario.cs
using Azure;
using Azure.Data.Tables;
using System.ComponentModel.DataAnnotations;


namespace AppAzure.Models
{
    public class Funcionario : ITableEntity
    {

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Ramal { get; set; }
        public string EmailProfissional { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal Salario { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTimeOffset? DataAdmissao { get; set; }

        public string Departamento { get; set; }

        public TipoAcao TipoAcao { get; set; }
        public string PartitionKey { get ; set ; }
        public string RowKey { get ; set ; }
        public DateTimeOffset? Timestamp { get ; set ; }
        public ETag ETag { get ; set ; }
    }
}

Models/FuncionarioLog.cs
using Azure;
using Azure.Data.Tables;
using System.Text.Json;

namespace AppAzure.Models
{
    public class FuncionarioLog : Funcionario, ITableEntity
    {
        public FuncionarioLog() { }

        public FuncionarioLog(Funcionario funcionario, TipoAcao tipoAcao, string partitionKey, string rowKey)
        {
            base.Id = funcionario.Id;
            base.Nome = funcionario.Nome;
            base.Endereco = funcionario.Endereco;
            base.Ramal = funcionario.Ramal;
            base.EmailProfissional = funcionario.EmailProfissional;
            base.Departamento = funcionario.Departamento;
            base.Salario = funcionario.Salario;
            base.DataAdmissao = funcionario.DataAdmissao;
            TipoAcao = tipoAcao;
            JSON = JsonSerializer.Serialize(funcionario);
            PartitionKey = partitionKey;
            RowKey = rowKey;
        }

        public TipoAcao TipoAcao { get; set; }
        public string JSON { get; set; }
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }



    }
}

Models/TipoAcao.cs
namespace AppAzure.Models
{
    public enum TipoAcao
    {
        Inclusao,
        Atualizacao,
        Remocao
    }

}

Controllers/FuncionarioController.cs
using AppAzure.Models;
using Azure.Data.Tables;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;


namespace AppAzure.Controllers
{
    public class FuncionarioController : Controller
    {

        private readonly string _connectionString;
        private readonly string _tableName;


        public FuncionarioController(IConfiguration configuration)
        {
            _connectionString = configuration.GetValue<string>("SAConnectionString");
            _tableName = configuration.GetValue<string>("AzureTableName");

        }

        private TableClient GetTableClient()
        {
            var serviceClient = new TableServiceClient(_connectionString);
            var tableClient = serviceClient.GetTableClient(_tableName);

            tableClient.CreateIfNotExists();

            return tableClient;
        }



        public IActionResult Index()
        {
            var tableClient = GetTableClient();
            var funcionarios = tableClient.Query<Funcionario>().ToList();


            return View(funcionarios);
        }

        public IActionResult Log()
        {
            var tableClient = GetTableClient();
            var funcionarios = tableClient.Query<Funcionario>().ToList();


            return View(funcionarios);
        }

        public IActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(Funcionario funcionario)
        {
            var tableClient = GetTableClient();
            funcionario.RowKey = Guid.NewGuid().ToString();
            funcionario.PartitionKey = funcionario.RowKey;
            funcionario.TipoAcao = TipoAcao.Inclusao;
            var transforma = funcionario.RowKey.Substring(funcionario.RowKey.Length - 8);
            string numeros = Regex.Replace(transforma, "[^0-9]", "");
            funcionario.Id = int.Parse(numeros);

            tableClient.UpsertEntity(funcionario);

            return View(funcionario);
        }


        public IActionResult Editar(string id)
        {
            var tableClient = GetTableClient();
            var funcionario = tableClient.GetEntity<Funcionario>(id, id).Value;

            if (funcionario == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(funcionario);
        }

        [HttpPost]
        public IActionResult Editar(Funcionario funcionario)
        {
            var tableClient = GetTableClient();
            var funcionarioBanco = tableClient.GetEntity<Funcionario>(funcionario.RowKey,funcionario.RowKey).Value;


            funcionarioBanco.Nome = funcionario.Nome;
            funcionarioBanco.Endereco = funcionario.Endereco;
            funcionarioBanco.Ramal = funcionario.Ramal;
            funcionarioBanco.EmailProfissional = funcionario.EmailProfissional;
            funcionarioBanco.Departamento = funcionario.Departamento;
            funcionarioBanco.Salario = funcionario.Salario;
            funcionarioBanco.DataAdmissao = funcionario.DataAdmissao;
            funcionarioBanco.TipoAcao = TipoAcao.Atualizacao;

            tableClient.UpsertEntity(funcionarioBanco);

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Detalhes(string id, Funcionario funcionario)
        {
            var tableClient = GetTableClient();
            var funcionarioTable = tableClient.GetEntity<Funcionario>(id, id).Value;

            if (funcionarioTable == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(funcionarioTable);
        }


        public IActionResult Excluir(string id)
        {
            var tableClient = GetTableClient();
            var funcionario = tableClient.GetEntity<Funcionario>(id, id).Value;

            if (funcionario == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(funcionario);

        }

        [HttpPost]
        public IActionResult Excluir(Funcionario funcionario)
        {
            var tableClient = GetTableClient();
            tableClient.DeleteEntity(funcionario.RowKey, funcionario.RowKey);

            return RedirectToAction(nameof(Index));

        }

    }
}

Controllers/HomeController.cs
using AppAzure.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppAzure.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Funcionario/Criar.cshtml
@model AppAzure.Models.Funcionario

@{
    ViewData["Title"] = "Criar Nova Tarefa";
}



<div>

    <h1>Novo Funcionário</h1>

    <div class="row ">

        <div class="shadow tela-contato">
            <form asp-action="Criar">
                <div class="form-group ">
                    <br />
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />


                </div>

                <div class="form-group input-icon">
                    <label asp-for="Endereco" class="control-label"></label>
                    <input asp-for="Endereco" class="form-control" />

                </div>

                <div class="form-group input-icon">
                    <label asp-for="Ramal" class="control-label"></label>
                    <input asp-for="Ramal" class="form-control" />
                </div>

                <div class="form-group input-icon">
                    <label asp-for="EmailProfissional" class="control-label"></label>
                    <input type="email" asp-for="EmailProfissional" class="form-control" />
                </div>

                <div class="form-group input-icon">
                    <label asp-for="Departamento" class="control-label"></label>
                    <input asp-for="Departamento" class="form-control" />
                </div>

                <div class="form-group input-icon">
                    <label asp-for="Salario" class="control-label"></label>
                    <input type="number" asp-for="Salario" class="form-control" />
                </div>


                <div class="form-group input-icon">
                    <label asp-for="DataAdmissao" class="control-label"></label>
                    <input type="date" asp-for="DataAdmissao" class="form-control" />
                </div>

                <br />

                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary" />


                </div>
                <br />
            </form>
        </div>
    </div>
    <br />
    <a asp-action="Index">Voltar</a>
    <br />
</div>

Views/Funcionario/Detalhes.cshtml
@model AppAzure.Models.Funcionario

@{
    ViewData["Title"] = "Detalhes do Funcionario";

}

<h1>Funcionário Detalhe</h1>

<div class="shadow tela-contato">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Endereco)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Endereco)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.EmailProfissional)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.EmailProfissional)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Ramal)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Ramal)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Departamento)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Departamento)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Salario)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Salario)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.DataAdmissao)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DataAdmissao)
        </dt>
    </dl>
</div>
<br />
<br />
<a asp-action="Index">Voltar</a>

Views/Funcionario/Editar.cshtml
@model AppAzure.Models.Funcionario

@{
    ViewData["Title"] = "Edita Funcionário";
}



<div class="">

    <h1>Edita Funcionário</h1>

    <div class="row ">

        <div class="col-md-6 shadow tela-contato">
            <form asp-action="Editar">
                <div class="form-group ">
                    <br />
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />


                </div>

                <div class="form-group input-icon">
                    <label asp-for="Endereco" class="control-label"></label>
                    <input asp-for="Endereco" class="form-control" />

                </div>

                <div class="form-group input-icon">
                    <label asp-for="Ramal" class="control-label"></label>
                    <input asp-for="Ramal" class="form-control" />
                </div>

                <div class="form-group input-icon">
                    <label asp-for="EmailProfissional" class="control-label"></label>
                    <input type="email" asp-for="EmailProfissional" class="form-control" />
                </div>

                <div class="form-group input-icon">
                    <label asp-for="Departamento" class="control-label"></label>
                    <input asp-for="Departamento" class="form-control" />
                </div>

                <div class="form-group input-icon">
                    <label asp-for="Salario" class="control-label"></label>
                    <input type="number" asp-for="Salario" class="form-control" />
                </div>


                <div class="form-group input-icon">
                    <label asp-for="DataAdmissao" class="control-label"></label>
                    <input type="date" asp-for="DataAdmissao" class="form-control" />
                </div>

                <div class="form-group input-icon">
                    <input type="hidden" asp-for="RowKey" class="form-control" />
                    <input type="hidden" asp-for="PartitionKey" class="form-control" />
                    <input type="hidden" asp-for="Timestamp" class="form-control" />
                    <input type="hidden" asp-for="ETag" class="form-control" />
                </div>

                <br />

                <div class="form-group">
                    <input type="submit" value="Atualizar" class="btn btn-primary" />


                </div>
                <br />
            </form>
         
        </div>
    </div>
    <br />
    <a asp-action="Index">Voltar</a>
    <br />
</div>

Views/Funcionario/Excluir.cshtml
@model AppAzure.Models.Funcionario

@{
    ViewData["Title"] = "Excluir do Contato";

}

<h1>Exclusão</h1>

<div class="shadow tela-contato">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Endereco)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Endereco)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.EmailProfissional)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.EmailProfissional)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Ramal)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Ramal)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Departamento)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Departamento)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Salario)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Salario)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.DataAdmissao)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DataAdmissao)
        </dt>

    </dl>

    <form asp-action="Excluir">
        <div class="form-group input-icon">
            <input type="hidden" asp-for="RowKey" class="form-control" />
            <input type="hidden" asp-for="PartitionKey" class="form-control" />
            <input type="hidden" asp-for="Timestamp" class="form-control" />
            <input type="hidden" asp-for="ETag" class="form-control" />
        </div>
        <input type="submit" value="Excluir" class="btn btn-danger" />
    </form>
</div>
<br />

<a asp-action="Index">Voltar</a>

Views/Funcionario/Index.cshtml
@using Azure.Core;
@using System.Globalization;
@model IEnumerable<AppAzure.Models.Funcionario>


@{
    ViewData["Title"] = "Listagem Funcionários";
}


<h2>Listagem de Funcionários</h2>
<br />
<p>
    <a asp-action="Criar">Novo Funcionário</a>
</p>
<br />

<p>
    <a asp-action="Log">Logo de acesso</a>
</p>
<br />


<div class="">
    <table class="tabela-contato shadow tela-contato">
        <thead>
            <tr class="cabecario">

                <th class="linha-cabecario">
                    NOME
                </th>
                <th>
                    ENDEREÇO
                </th>
                <th>
                    DEPARTAMENTO
                </th>
                <th>
                    EMAIL PROFISSIONAL
                </th>
                <th>
                    SALÁRIO
                </th>
                <th>
                    ADMISSÃO
                </th>
                <th>
                    OPÇÕES
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)

            {
                
                                     
                <tr>

                    <td class="linha-cabecario">
                        @Html.DisplayFor(model => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Endereco)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Departamento)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.EmailProfissional)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Salario)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.DataAdmissao)
                    </td>
                    <td class="selecao-icon">
                        <a asp-action="Editar" asp-route-id="@item.RowKey">  <i class="fa fa-pencil"></i></a>
                        <a asp-action="Detalhes" asp-route-id="@item.RowKey"><i class="fa fa-eye"></i></a>
                        <a asp-action="Excluir" asp-route-id="@item.RowKey"> <i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Funcionario/Log.cshtml
@model List<AppAzure.Models.Funcionario>

@{
    ViewData["Title"] = "Listagem log de Acesso";
}
<br />

<h2>Log da Tabela</h2>
<br />


<div >
    <table class="tabela-contato shadow tela-contato">
        <thead>
            <tr class="cabecario">
                
                <th class="linha-cabecario">TIPO DE AÇÃO</th>
                <th>DATA</th>
                <th>ROWKEY</th>
                <th>ETAG</th>
                <th>PARTITIONKEY</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="linha-cabecario">
                        @Html.DisplayFor(model => item.TipoAcao)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.Timestamp)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.RowKey)
                    </td>

                    <td>
                       @Html.DisplayFor(model => item.ETag)
                   </td>

                   <td>
                       @Html.DisplayFor(model => item.PartitionKey)
                    </td>
                    
                </tr>
            }
        </tbody>
       
    </table>
    <br />
    <a asp-action="Index">Voltar</a>
</div>

Views/Funcionario/PesquisaDepartamento.cshtml
@model List<AppAzure.Models.Funcionario>

@{
    ViewData["Title"] = "Pesquisa por Departamento";
}
<br />

<h2>Filtro por Nome do Funcionário</h2>
<br />


<div class="pesquisa">
    <table class="tabela-contato shadow tela-contato ">
        <thead>
            <tr class="cabecario">
                <th class="linha-cabecario">ID</th>
                <th>NOME</th>
                <th>DEPARTAMENTO</th>
                <th>ADMISSÃO</th>
                <th>SALARIO</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="linha-cabecario">
                        @Html.DisplayFor(model => item.Id)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.Nome)
                    </td>

                    <td>
                    @Html.DisplayFor(model => item.Departamento)
                    </td>

                    <td>
                       @Html.DisplayFor(model => item.DataAdmissao)
                   </td>

                   <td>
                       @Html.DisplayFor(model => item.Salario)
                    </td>
                    
                </tr>
            }
        </tbody>
       
    </table>
    <br />
    <a asp-action="Index">Voltar</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">RH Sistema</h1>
    <p>SQL Server - APP na Nuvem - Desvendando os segredos do Azure</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppAzure</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppAzure.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppAzure</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppAzure - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>